name: patch-font
on: [push]
env:
  FONT_FORGE_URL: https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage
  FONT_FORGE: FontForge.AppImage
  FONT_PATCHER_URL: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/FontPatcher.zip
  FONT_PATCHER: FontPatcher.zip
  FONT_FILE: Monocraft.ttf
jobs:
  patch-font:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FontForge
        run: |
          wget $FONT_FORGE_URL -O $FONT_FORGE
          chmod u+x $FONT_FORGE

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          pip install -U python-fontforge argparse

      - name: Download and extract patch script
        run: |
          wget $FONT_PATCHER_URL -O $FONT_PATCHER
          unzip $FONT_PATCHER

      - name: Patch font
        run: ./$FONT_FORGE -script $PWD/font-patcher $PWD/$FONT_FILE -out ./patched-font

      - name: Upload patched font
        uses: actions/upload-artifact@v3
        with:
          name: patched font
          path: ./patched-font
